"""initial create users and requests

Revision ID: 276ba6d9be7c
Revises: 1318d5737087
Create Date: 2025-12-15 12:44:48.141159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276ba6d9be7c'
down_revision: Union[str, Sequence[str], None] = '1318d5737087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('format_chosen', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.add_column('users', sa.Column('pregnancy_term', sa.String(), nullable=True))
    op.add_column('users', sa.Column('yoga_experience', sa.String(), nullable=True))
    op.add_column('users', sa.Column('contraindications', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contraindications')
    op.drop_column('users', 'yoga_experience')
    op.drop_column('users', 'pregnancy_term')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
