"""Add current_step to Application

Revision ID: 48639fc16246
Revises: aac1505c7549
Create Date: 2026-01-21 14:27:54.689357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48639fc16246'
down_revision: Union[str, Sequence[str], None] = 'aac1505c7549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('current_step', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'current_step')
    # ### end Alembic commands ###
