"""Add Application table

Revision ID: aac1505c7549
Revises: 276ba6d9be7c
Create Date: 2026-01-21 13:47:21.217735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac1505c7549'
down_revision: Union[str, Sequence[str], None] = '276ba6d9be7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('pregnancy_term', sa.String(), nullable=True),
    sa.Column('yoga_experience', sa.String(), nullable=True),
    sa.Column('contraindications', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_column('users', 'pregnancy_term')
    op.drop_column('users', 'contraindications')
    op.drop_column('users', 'yoga_experience')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('yoga_experience', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('contraindications', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('pregnancy_term', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.drop_table('applications')
    # ### end Alembic commands ###
